# https://github.com/mrcjkb/haskell-tools.nvim/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml
name: Bug Report
description: Report a problem with guard.nvim
labels: [bug]
body:

  - type: input
    attributes:
      label: "Neovim version (nvim -v)"
      placeholder: "v0.10.0"
    validations:
      required: true
  - type: input
    attributes:
      label: "Operating system/version"
      placeholder: "Fedora Linux 40"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Output of :checkhealth guard"
      render: "console"
      placeholder: |
        Perhaps the tools are not in your $PATH?
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Output of :Guard info"
      render: "markdown"
      placeholder: |
        Are the autocmds attached?
    validations:
      required: true
  - type: textarea
    attributes:
      label: "How to reproduce the issue"
      placeholder: |
        git clone https://github.com/nvimdev/guard.nvim /tmp
        git clone https://github.com/nvimdev/guard-collection /tmp
        echo "vim.opt.rtp:append('/tmp/guard.nvim')" >> /tmp/repro.lua
        echo "vim.opt.rtp:append('/tmp/guard-collection')" >> /tmp/repro.lua
        nvim --clean -u /tmp/repro.lua
    validations:
      required: true
  - type: checkboxes
    attributes:
      - options:
        - label: I understand that if my repro step is too complicated (e.g. here is my 1k+ line config and please help me), developers might not be able to help.
          required: true
        - label: I can confirm that my reproduction step only involves `vim.opt.rtp` and configuration themselves
          required: true
  - type: textarea
    attributes:
      label: "Expected behaviour"
      description: "Describe the behaviour you expect."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Actual behaviour"
    validations:
      required: true
